### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by oliverjam** [Jamchiller/jaredhill.co#1]
Shit I'm really sorry but I forgot to put analytics in. Will sort asap today

**Comment by Jamchiller** [comment]
Thanks man

**Comment by Jamchiller** [comment]
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-73022918-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-73022918-4');
</script>`

**Comment by Jamchiller** [comment]
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-73022918-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-73022918-4');
</script>
```

**Comment by oliverjam** [comment]
Huh, that looks different to the last time I did this. What's Google Tag Manager?

**Comment by Jamchiller** [comment]
Idk I thought that was the one!!
________________________________

**Comment by Jamchiller** [comment]
![screen shot 2017-11-15 at 12 23 38 pm](https://user-images.githubusercontent.com/16238581/32835941-f79c7174-c9ff-11e7-9831-8cc8fe01f0e1.png)

**Comment by Jamchiller** [comment]
See above

**Comment by oliverjam** [comment]
So I added the code, but I can't deploy anymore (because it's on your Surge account). So you need to pull the changes and then deploy. Also you'll have to check it's actually working cause I don't have access to your analytics.

**Comment by Jamchiller** [comment]
I pulled the changes and deployed on Friday but it's not working! Nothing showing up on analytics. Weird. It says in the instructions that it needs to be the first item in the <HEAD> tag, but I noticed you put it further down, could this be the issue? @oliverjam

**Comment by oliverjam** [comment]
Weird. Where it is shouldn't affect anything. I'll take another look

**Comment by Jamchiller** [comment]
Any luck? The only thing that Google is telling me on the Analytics page is that it can't find the analytics code and that I should try Google Tag Assistant to check

https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk/?utm_source=google.com&utm_medium=referral&utm_campaign=gtar_diag_notification

@oliverjam

**Comment by oliverjam** [comment]
Okay I've tries using the official Gatsby GA plugin that auto-generates the script tags. You'll have to build and redeploy to see if it worked

**Comment by Jamchiller** [comment]
Cool, I've deployed and will check if it's working soon! Thanks man

**Comment by Jamchiller** [comment]
Workkkkking whoop
