### ISSUE TITLE
Alt text on links

### ISSUE THREAD

**Issue by oliverjam** [Jamchiller/jaredhill.co#7]
I noticed you added alt text to some of the links.`alt` isn't a valid attribute for `a` tags (it's for `img`). Links are already text and are accessible by default (assuming you make the link text something useful instead of just "click here").

**Comment by Jamchiller** [comment]
Ah yes I wanted some text to appear on hover so that people would know where the link is taking them and it didn't work, obviously. Hence the alt tag

**Comment by oliverjam** [comment]
Err I think you can use `title` for that. It gives you the little tooltip thing when you hover the link

**Comment by Jamchiller** [comment]
nice. Thanks. I'll do that

**Comment by oliverjam** [comment]
@Jamchiller Just read an article on the `title` attribute

https://developer.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/

>If you want to hide content from mobile and tablet users as well as assistive tech users and keyboard only users, use the `title` attribute.

>Examples of title attribute use that are NOT USEFUL or are of LIMITED USE:
>- For additional information not provided as text in a link or surrounding content:
>    - `<a href="newsletter.PDF" title="PDF file, size 1 mb.">newsletter</a>`
>    - Instead include such information as part of the link text or next to the link.

From the [official HTML5 recommendation](https://www.w3.org/TR/html/dom.html#the-title-attribute):

>Relying on the title attribute for the visual display of text content is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g. requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet).
